name: Lint

on:
  push:
    branches: [ master ]
  #release:
  #  type: [ created ]
  #pull_request:
  #  branches: [ master ]

jobs:
  setup_dev_env:
    name: Setup Project Development Environment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer development dependencies
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-composer-dev-deps-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-dev-deps-

    - name: Install Composer development dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --dev --prefer-source --no-progress --no-suggest --no-interaction

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        check-latest: true

    - name: Cache NPM development dependencies
      id: npm-cache
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-npm-dev-deps-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-dev-deps-

    - name: Install NPM development dependencies
      if: steps.npm-cache.outputs.cache-hit != 'true'
      run: npm install --production=false

    #- name: Lint package.json
    #  run: npm run lint:pkg-json

  #lint_styles:
  #  name: Lint Styles
  #  runs-on: ubuntu-latest
  #  needs: setup_dev_env
  #  steps:
  #  - uses: actions/checkout@v2
  #
  #  - name: Setup Node.js environment
  #    uses: actions/setup-node@v2
  #    with:
  #      node-version: 14.x
  #
  #  - name: Load NPM development dependency cache
  #    id: npm-cache
  #    uses: actions/cache@v2
  #    with:
  #      path: node_modules
  #      key: ${{ runner.os }}-npm-dev-deps-${{ hashFiles('**/package-lock.json') }}
  #      restore-keys:
  #        ${{ runner.os }}-npm-dev-deps-
  #
  #  - name: Lint Styles
  #    run: npm run lint:css

  lint_scripts:
    name: Lint Scripts
    runs-on: ubuntu-latest
    needs: setup_dev_env
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: 14.x

    - name: Load NPM development dependency cache
      id: npm-cache
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-npm-dev-deps-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-dev-deps-

    - name: Lint Scripts
      run: npm run lint:js

  phpcs:
    name: PHPCodeSniffer
    runs-on: ubuntu-latest
    needs: setup_dev_env
    steps:
    - uses: actions/checkout@v2

    - name: Load Composer development dependency cache
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-composer-dev-deps-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-dev-deps-

    - name: PHPCS
      run: ./vendor/bin/phpcs ./gf-poplink.php ./inc
